// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ZjE2o_prDANEgwmWSkBmyccIVEmP7D8',
    appId: '1:973633731440:web:cfaa9d12aeec21d5aa2db5',
    messagingSenderId: '973633731440',
    projectId: 'chat-app-d1f40',
    authDomain: 'chat-app-d1f40.firebaseapp.com',
    storageBucket: 'chat-app-d1f40.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqTnBxyqo2Mt4dzTtXjH4plmDit2HVu34',
    appId: '1:973633731440:android:b4317c9499b2e220aa2db5',
    messagingSenderId: '973633731440',
    projectId: 'chat-app-d1f40',
    storageBucket: 'chat-app-d1f40.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9ZjE2o_prDANEgwmWSkBmyccIVEmP7D8',
    appId: '1:973633731440:web:4c1b7ab1f9acc8a6aa2db5',
    messagingSenderId: '973633731440',
    projectId: 'chat-app-d1f40',
    authDomain: 'chat-app-d1f40.firebaseapp.com',
    storageBucket: 'chat-app-d1f40.firebasestorage.app',
  );
}
